[package]
name = "bitf"
version = "0.9.0"
authors = ["hrafnskogr <hrafnskogr@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version=">=1.0.84", features=["full", "fold"] }
quote = ">=1.0.10"
proc-macro2 = ">=1.0.34"
